import streamlit as st
import pandas as pd
import plotly.express as px
import os

from components import page_title, section


def alerts_page():

    page_title(
        "🚨 Alert Center",
        "Security alerts generated by the AI-Driven IDPS."
    )

    st.divider()

    # =====================================================
    # LOAD ALERTS
    # =====================================================

    alert_file = "logs/alerts.csv"

    if not os.path.exists(alert_file):

        st.info("No alerts generated yet.")

        return

    alerts = pd.read_csv(alert_file)

    if alerts.empty:

        st.info("No alerts generated yet.")

        return

    # =====================================================
    # KPI CARDS
    # =====================================================

    total_alerts = len(alerts)

    blocked_ips = alerts["Blocked_IP"].nunique()

    high = len(alerts[alerts["Risk_Level"] == "HIGH"])

    medium = len(alerts[alerts["Risk_Level"] == "MEDIUM"])

    low = len(alerts[alerts["Risk_Level"] == "LOW"])

    c1, c2, c3, c4 = st.columns(4)

    c1.metric("🚨 Total Alerts", total_alerts)

    c2.metric("🛑 Blocked IPs", blocked_ips)

    c3.metric("🔴 High Risk", high)

    c4.metric("🟡 Medium Risk", medium)

    st.divider()

    # =====================================================
    # CHARTS
    # =====================================================

    left, right = st.columns([2,1])

    with left:

        section("Threat Severity")

        risk = alerts["Risk_Level"].value_counts()

        fig = px.pie(
            values=risk.values,
            names=risk.index,
            hole=0.45
        )

        st.plotly_chart(
            fig,
            use_container_width=True
        )

    with right:

        section("Top Attack Types")

        attack = alerts["Predicted_Attack"].value_counts()

        fig = px.bar(
            attack,
            x=attack.values,
            y=attack.index,
            orientation="h"
        )

        st.plotly_chart(
            fig,
            use_container_width=True
        )

    st.divider()

    # =====================================================
    # ALERT LOG
    # =====================================================

    section("Recent Alerts")

    st.dataframe(

        alerts.sort_values(

            "Timestamp",

            ascending=False

        ),

        use_container_width=True,

        hide_index=True

    )

    st.divider()

    # =====================================================
    # BLOCKED IPS
    # =====================================================

    section("Blocked IP Addresses")

    blocked = alerts["Blocked_IP"].dropna().unique()

    if len(blocked):

        for ip in blocked:

            st.error(f"🚫 {ip}")

    else:

        st.success("No blocked IPs.")

    st.divider()

    # =====================================================
    # DOWNLOAD
    # =====================================================

    with open(alert_file, "rb") as f:

        st.download_button(

            "⬇ Download Incident Report",

            f,

            file_name="alerts.csv",

            mime="text/csv"

        )